spring.application.name=course-registration

# =====================
# Database (H2 File)
# =====================
spring.datasource.url=jdbc:h2:file:./testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# =====================
# JPA / Hibernate
# =====================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# =====================
# ActiveMQ (Embedded Broker)
# =====================
# spring.activemq.broker-url=vm://embedded?broker.persistent=false
spring.activemq.in-memory=true

# = [Server]
# =====================
server.port=8080

# =====================
# Email (SMTP Configuration)
# =====================
# For Gmail: Use an "App Password" (NOT your regular password)
# 1. Go to Google Account -> Security -> 2-Step Verification
# 2. Select "App passwords" at the bottom
# 3. Choose "Mail" and this PC to generate a 16-character code
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=psychosadist81@gmail.com
spring.mail.password=uthl ijtx epmx wavt
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
# spring.mail.properties.mail.debug=true